apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open5gs

resources:
  - webui-configmap.yaml
  - webui-deployment.yaml
  - webui-service.yaml

images:
  - name: ghcr.io/niloysh/open5gs-webui
    newTag: v2.7.0
