logger:
  file: /open5gs/install/var/log/open5gs/amf.log

global:
  max:
    ue: 1024

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 80
    client:
      scp:
        - uri: http://127.0.1.10:80
  ngap:
    server:
      - address: 10.10.2.2
  metrics:
    server:
      - address: 127.0.0.5
        port: 9090
  guami:
    - plmn_id:
        mcc: 302
        mnc: 721
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 302
        mnc: 721
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 302
        mnc: 721
      s_nssai:
        - sst: 1
          sd: 000001
        - sst: 2
          sd: 000002
  security:
    integrity_order: [NIA2, NIA1, NIA0]
    ciphering_order: [NEA0, NEA1, NEA2]
  network_name:
    full: Open5GS
  amf_name: open5gs-amf0

  time:
    t3512:
      value: 540
