apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../open5gs

images:
  - name: ghcr.io/niloysh/open5gs
    newTag: v2.7.0-upf-metrics-v2

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            containers:
              - name: upf
                resources:
                  requests:
                    memory: "1000Mi"
                    cpu: "1000m"
                  limits:
                    memory: "2000Mi"
                    cpu: "2000m"

    target:
      kind: Deployment
      name: open5gs-upf.*
