apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../open5gs-metrics

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                      - nuc1
                      - nuc2
    target:
      kind: Deployment
