---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue1
  labels:
    app: ueransim
    component: ue
    name: ue1
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue1
  replicas: 1
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue1
    spec:
      initContainers:
      - name: wait-gnb
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: gnb-service:4997
        command: ["sh", "-c", "until nc -z -u $DEPENDENCIES; do echo waiting for the gNB; sleep 2; done;"]
      containers:
        - image: ghcr.io/niloysh/ueransim:v3.2.6
          imagePullPolicy: Always
          name: ue
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command: ["/bin/bash", "-c", "--"]
          args:
            - |
              if [ "$DEBUG_MODE" = "true" ]; then
                while true; do sleep 30; done;
              else
                /ueransim/config/wrapper.sh
              fi
          env:
            - name: DEBUG_MODE
              value: "false"
          volumeMounts:
            - mountPath: /ueransim/config
              name: ue-volume
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue-volume
          configMap:
            name: ue1-configmap
            items:
              - key: ue1.yaml
                path: ue1.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0755
